import * as productionCalls from '../../production/sudo/calls'
import * as stageCalls from '../../stage/sudo/calls'
import * as testCalls from '../../test/sudo/calls'
import * as devCalls from '../../dev/sudo/calls'


export const sudo = {
	name: 'Sudo.sudo',
	v22: productionCalls.sudo['v22'],
	v33Stage: stageCalls.sudo['v33'],
	v35Stage: stageCalls.sudo['v35'],
	v37Stage: stageCalls.sudo['v37'],
	v38Stage: stageCalls.sudo['v38'],
	v42Stage: stageCalls.sudo['v42'],
	v43Stage: stageCalls.sudo['v43'],
	v44Stage: stageCalls.sudo['v44'],
	v45Stage: stageCalls.sudo['v45'],
	v46Stage: stageCalls.sudo['v46'],
	v47Stage: stageCalls.sudo['v47'],
	v48Stage: stageCalls.sudo['v48'],
	v52Stage: stageCalls.sudo['v52'],
	v54Stage: stageCalls.sudo['v54'],
	v55Stage: stageCalls.sudo['v55'],
	v57Stage: stageCalls.sudo['v57'],
	v59Stage: stageCalls.sudo['v59'],
	v60Stage: stageCalls.sudo['v60'],
	v62Stage: stageCalls.sudo['v62'],
	v64Stage: stageCalls.sudo['v64'],
	v66Stage: stageCalls.sudo['v66'],
	v69Stage: stageCalls.sudo['v69'],
	v70Stage: stageCalls.sudo['v70'],
	v71Stage: stageCalls.sudo['v71'],
	v33Test: testCalls.sudo['v33'],
	v35Test: testCalls.sudo['v35'],
	v37Test: testCalls.sudo['v37'],
	v38Test: testCalls.sudo['v38'],
	v42Test: testCalls.sudo['v42'],
	v43Test: testCalls.sudo['v43'],
	v44Test: testCalls.sudo['v44'],
	v45Test: testCalls.sudo['v45'],
	v46Test: testCalls.sudo['v46'],
	v47Test: testCalls.sudo['v47'],
	v48Test: testCalls.sudo['v48'],
	v52Test: testCalls.sudo['v52'],
	v54Test: testCalls.sudo['v54'],
	v55Test: testCalls.sudo['v55'],
	v57Test: testCalls.sudo['v57'],
	v59Test: testCalls.sudo['v59'],
	v60Test: testCalls.sudo['v60'],
	v62Test: testCalls.sudo['v62'],
	v64Test: testCalls.sudo['v64'],
	v66Test: testCalls.sudo['v66'],
	v69Test: testCalls.sudo['v69'],
	v70Test: testCalls.sudo['v70'],
	v71Test: testCalls.sudo['v71'],
	v70Dev: devCalls.sudo['v70'],
}

export const sudoUncheckedWeight = {
	name: 'Sudo.sudo_unchecked_weight',
	v22: productionCalls.sudoUncheckedWeight['v22'],
	v33Stage: stageCalls.sudoUncheckedWeight['v33'],
	v35Stage: stageCalls.sudoUncheckedWeight['v35'],
	v37Stage: stageCalls.sudoUncheckedWeight['v37'],
	v38Stage: stageCalls.sudoUncheckedWeight['v38'],
	v42Stage: stageCalls.sudoUncheckedWeight['v42'],
	v43Stage: stageCalls.sudoUncheckedWeight['v43'],
	v44Stage: stageCalls.sudoUncheckedWeight['v44'],
	v45Stage: stageCalls.sudoUncheckedWeight['v45'],
	v46Stage: stageCalls.sudoUncheckedWeight['v46'],
	v47Stage: stageCalls.sudoUncheckedWeight['v47'],
	v48Stage: stageCalls.sudoUncheckedWeight['v48'],
	v52Stage: stageCalls.sudoUncheckedWeight['v52'],
	v54Stage: stageCalls.sudoUncheckedWeight['v54'],
	v55Stage: stageCalls.sudoUncheckedWeight['v55'],
	v57Stage: stageCalls.sudoUncheckedWeight['v57'],
	v59Stage: stageCalls.sudoUncheckedWeight['v59'],
	v60Stage: stageCalls.sudoUncheckedWeight['v60'],
	v62Stage: stageCalls.sudoUncheckedWeight['v62'],
	v64Stage: stageCalls.sudoUncheckedWeight['v64'],
	v66Stage: stageCalls.sudoUncheckedWeight['v66'],
	v69Stage: stageCalls.sudoUncheckedWeight['v69'],
	v70Stage: stageCalls.sudoUncheckedWeight['v70'],
	v71Stage: stageCalls.sudoUncheckedWeight['v71'],
	v33Test: testCalls.sudoUncheckedWeight['v33'],
	v35Test: testCalls.sudoUncheckedWeight['v35'],
	v37Test: testCalls.sudoUncheckedWeight['v37'],
	v38Test: testCalls.sudoUncheckedWeight['v38'],
	v42Test: testCalls.sudoUncheckedWeight['v42'],
	v43Test: testCalls.sudoUncheckedWeight['v43'],
	v44Test: testCalls.sudoUncheckedWeight['v44'],
	v45Test: testCalls.sudoUncheckedWeight['v45'],
	v46Test: testCalls.sudoUncheckedWeight['v46'],
	v47Test: testCalls.sudoUncheckedWeight['v47'],
	v48Test: testCalls.sudoUncheckedWeight['v48'],
	v52Test: testCalls.sudoUncheckedWeight['v52'],
	v54Test: testCalls.sudoUncheckedWeight['v54'],
	v55Test: testCalls.sudoUncheckedWeight['v55'],
	v57Test: testCalls.sudoUncheckedWeight['v57'],
	v59Test: testCalls.sudoUncheckedWeight['v59'],
	v60Test: testCalls.sudoUncheckedWeight['v60'],
	v62Test: testCalls.sudoUncheckedWeight['v62'],
	v64Test: testCalls.sudoUncheckedWeight['v64'],
	v66Test: testCalls.sudoUncheckedWeight['v66'],
	v69Test: testCalls.sudoUncheckedWeight['v69'],
	v70Test: testCalls.sudoUncheckedWeight['v70'],
	v71Test: testCalls.sudoUncheckedWeight['v71'],
	v70Dev: devCalls.sudoUncheckedWeight['v70'],
}

export const setKey = {
	name: 'Sudo.set_key',
	v22: productionCalls.setKey['v22'],
	v33Stage: stageCalls.setKey['v33'],
	v33Test: testCalls.setKey['v33'],
	v70Dev: devCalls.setKey['v70'],
}

export const sudoAs = {
	name: 'Sudo.sudo_as',
	v22: productionCalls.sudoAs['v22'],
	v33Stage: stageCalls.sudoAs['v33'],
	v35Stage: stageCalls.sudoAs['v35'],
	v37Stage: stageCalls.sudoAs['v37'],
	v38Stage: stageCalls.sudoAs['v38'],
	v42Stage: stageCalls.sudoAs['v42'],
	v43Stage: stageCalls.sudoAs['v43'],
	v44Stage: stageCalls.sudoAs['v44'],
	v45Stage: stageCalls.sudoAs['v45'],
	v46Stage: stageCalls.sudoAs['v46'],
	v47Stage: stageCalls.sudoAs['v47'],
	v48Stage: stageCalls.sudoAs['v48'],
	v52Stage: stageCalls.sudoAs['v52'],
	v54Stage: stageCalls.sudoAs['v54'],
	v55Stage: stageCalls.sudoAs['v55'],
	v57Stage: stageCalls.sudoAs['v57'],
	v59Stage: stageCalls.sudoAs['v59'],
	v60Stage: stageCalls.sudoAs['v60'],
	v62Stage: stageCalls.sudoAs['v62'],
	v64Stage: stageCalls.sudoAs['v64'],
	v66Stage: stageCalls.sudoAs['v66'],
	v69Stage: stageCalls.sudoAs['v69'],
	v70Stage: stageCalls.sudoAs['v70'],
	v71Stage: stageCalls.sudoAs['v71'],
	v33Test: testCalls.sudoAs['v33'],
	v35Test: testCalls.sudoAs['v35'],
	v37Test: testCalls.sudoAs['v37'],
	v38Test: testCalls.sudoAs['v38'],
	v42Test: testCalls.sudoAs['v42'],
	v43Test: testCalls.sudoAs['v43'],
	v44Test: testCalls.sudoAs['v44'],
	v45Test: testCalls.sudoAs['v45'],
	v46Test: testCalls.sudoAs['v46'],
	v47Test: testCalls.sudoAs['v47'],
	v48Test: testCalls.sudoAs['v48'],
	v52Test: testCalls.sudoAs['v52'],
	v54Test: testCalls.sudoAs['v54'],
	v55Test: testCalls.sudoAs['v55'],
	v57Test: testCalls.sudoAs['v57'],
	v59Test: testCalls.sudoAs['v59'],
	v60Test: testCalls.sudoAs['v60'],
	v62Test: testCalls.sudoAs['v62'],
	v64Test: testCalls.sudoAs['v64'],
	v66Test: testCalls.sudoAs['v66'],
	v69Test: testCalls.sudoAs['v69'],
	v70Test: testCalls.sudoAs['v70'],
	v71Test: testCalls.sudoAs['v71'],
	v70Dev: devCalls.sudoAs['v70'],
}
