version: '3'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
    healthcheck:
      test: pg_isready -U postgres

  subquery-node:
    image: onfinality/subql-node:v4.4.1
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    volumes:
      - ./:/app
    command:
      - -f=/app
      - --log-level=debug
      - --disable-historical=true
      - --subscription
      - --allow-schema-migration=true

  graphql-engine:
    image: onfinality/subql-query:v2.11.1
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    command:
      - --name=app
      - --playground
      - --subscription