specVersion: 1.0.0
name: sora-subquery
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: 1.9.1
  query:
    name: '@subql/query'
    version: 1.5.0
description: ''
repository: 'https://github.com/sora-xor/sora-subquery'
schema:
  file: ./schema.graphql
network:
  chainId: '0x406bd6d2023526fe7a25ea68fda60fec5e1c6ccac7b70395ce84787f03954b2a'
  endpoint: wss://ws.framenode-1.v1.tst.sora2.soramitsu.co.jp
  chaintypes:
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: getAllAssetsInfos
          kind: substrate/BlockHandler
        - handler: assetRegistrationHandler
          kind: substrate/CallHandler
          filter:
            module: assets
            method: register

        # sync pools reserves & prices, create snapshots
        - handler: syncXYKPools
          kind: substrate/BlockHandler
        # - handler: syncTBCPools
        #   kind: substrate/BlockHandler
        - handler: handlerTransfers
          kind: substrate/CallHandler
          filter:
            module: assets
            method: transfer
        - handler: handleSwaps
          kind: substrate/CallHandler
          filter:
            module: liquidityProxy
            method: swap
        - handler: handleSwapTransfers
          kind: substrate/CallHandler
          filter:
            module: liquidityProxy
            method: swapTransfer
        - handler: handleLiquidityDeposit
          kind: substrate/CallHandler
          filter:
            module: poolXYK
            method: depositLiquidity
        - handler: handleLiquidityRemoval
          kind: substrate/CallHandler
          filter:
            module: poolXYK
            method: withdrawLiquidity
        - handler: handlerIrohaMigration
          kind: substrate/CallHandler
          filter:
            module: irohaMigration
            method: migrate
        - handler: batchTransactionsHandler
          kind: substrate/CallHandler
          filter:
            module: utility
            method: batchAll
        - handler: handleBurnedAssetsAmount
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Withdrawn
        - handler: handleRemintedAssetsAmount
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Deposited
        - handler: handleClaimableReward
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Transferred
        - handler: soraEthTransferHandler
          kind: substrate/CallHandler
          filter:
            module: ethBridge
            method: transferToSidechain
        - handler: ethSoraTransferHandler
          kind: substrate/EventHandler
          filter:
            module: ethBridge
            method: IncomingRequestFinalized
        - handler: ethSoraTransferHandler
          kind: substrate/EventHandler
          filter:
            module: ethBridge
            method: IncomingRequestFinalizationFailed
        - handler: rewardsHandler
          kind: substrate/CallHandler
          filter:
            module: pswapDistribution
            method: claimIncentive
        - handler: rewardsHandler
          kind: substrate/CallHandler
          filter:
            module: rewards
            method: claim
        - handler: rewardsHandler
          kind: substrate/CallHandler
          filter:
            module: vestedRewards
            method: claimRewards
        - handler: rewardsHandler
          kind: substrate/CallHandler
          filter:
            module: vestedRewards
            method: claimCrowdloanRewards
        - handler: setReferralHandler
          kind: substrate/CallHandler
          filter:
            module: referrals
            method: setReferrer
        - handler: referralReserveHandler
          kind: substrate/CallHandler
          filter:
            module: referrals
            method: reserve
        - handler: referralUnreserveHandler
          kind: substrate/CallHandler
          filter:
            module: referrals
            method: unreserve
        - handler: referrerRewardHandler
          kind: substrate/EventHandler
          filter:
            module: xorFee
            method: ReferrerRewarded
        - handler: demeterDepositHandler
          kind: substrate/CallHandler
          filter:
            module: demeterFarmingPlatform
            method: deposit
        - handler: demeterWithdrawHandler
          kind: substrate/CallHandler
          filter:
            module: demeterFarmingPlatform
            method: withdraw
        - handler: demeterGetRewardsHandler
          kind: substrate/CallHandler
          filter:
            module: demeterFarmingPlatform
            method: getRewards
