specVersion: 0.2.0
name: 'sora-subquery'
version: 1.0.0
description: ''
repository: https://github.com/sora-xor/sora-subquery
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x7e4e32d0feafd4f9c9414b0be86373f9a1efa904809b683453a9af6856d38ad5'
  endpoint: wss://mof3.sora.org
  chaintypes:
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 0
    mapping:
      file: ./dist/index.js
      handlers:

        # - handler: handleXYKPools
        #   kind: substrate/BlockHandler

        - handler: handlerTransfers
          kind: substrate/CallHandler
          filter:
            module: assets
            method: transfer
        - handler: handleSwaps
          kind: substrate/CallHandler
          filter:
            module: liquidityProxy
            method: swap
        - handler: handleLiquidityDeposit
          kind: substrate/CallHandler
          filter:
            module: poolXyk
            method: depositLiquidity
        - handler: handleLiquidityRemoval
          kind: substrate/CallHandler
          filter:
            module: poolXyk
            method: withdrawLiquidity
        - handler: handlerIrohaMigration
          kind: substrate/CallHandler
          filter:
            module: irohaMigration
            method: migrate
        - handler: batchTransactionsHandler
          kind: substrate/CallHandler
          filter:
            module: utility
            method: batchAll
        - handler: handleBurnedAssetsAmount
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Withdrawn
        - handler: handleRemintedAssetsAmount
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Deposited
        - handler: handleClaimableReward
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Transferred
        - handler: assetRegistrationHandler
          kind: substrate/CallHandler
          filter:
            module: assets
            method: register
        - handler: soraEthTransferHandler
          kind: substrate/CallHandler
          filter:
            module: ethBridge
            method: transferToSidechain
        - handler: ethSoraTransferHandler
          kind: substrate/EventHandler
          filter:
            module: ethBridge
            method: IncomingRequestFinalized
        - handler: ethSoraTransferHandler
          kind: substrate/EventHandler
          filter:
            module: ethBridge
            method: IncomingRequestFinalizationFailed
        - handler: rewardsHandler
          kind: substrate/CallHandler
          filter:
            module: pswapDistribution
            method: claimIncentive
        - handler: rewardsHandler
          kind: substrate/CallHandler
          filter:
            module: rewards
            method: claim
        - handler: rewardsHandler
          kind: substrate/CallHandler
          filter:
            module: vestedRewards
            method: claimRewards
        - handler: referrerRewardHandler
          kind: substrate/EventHandler
          filter:
            module: xorFee
            method: ReferrerRewarded
