enum HistoryElementType {
  CALL
  EVENT
}

type HistoryElement @entity {
  id: ID!
  type: HistoryElementType!
  blockHeight: Int!
  blockHash: String! @index
  module: String! @index
  method: String! @index
  address: String! @index
  networkFee: String!
  execution: ExecutionResult!
  timestamp: Int!
  data: HistoryElementDetails
  dataTo: String @index
  dataFrom: String @index
  dataAssets: [String]
  calls: [HistoryElementCall!]! @derivedFrom(field: "historyElement")
  callNames: [String]!
  updatedAtBlock: Int!
}

type HistoryElementDetails @jsonField {
  data: String # API is implemented by bypassing the scheme - `data` in all mappings is an object, not a String. See https://github.com/subquery/subql/issues/522.
}

type HistoryElementCall @entity {
  id: ID!
  historyElement: HistoryElement! @index
  module: String!
  method: String!
  hash: String! @index
  data: HistoryElementCallDetails
  updatedAtBlock: Int!
}

type HistoryElementCallDetails @jsonField {
  data: String # API is implemented by bypassing the scheme - `data` in all mappings is an object, not a String. See https://github.com/subquery/subql/issues/522.
}

type ExecutionResult @jsonField {
  success: Boolean!
  error: Error
}

type Error @jsonField {
  moduleErrorId: Int
  moduleErrorIndex: Int
  nonModuleErrorMessage: String
}

enum PayeeType {
  STAKED
  STASH
  CONTROLLER
  ACCOUNT
  NONE
}

type StakingStaker @entity {
  id: ID!
  eraValidators: [StakingEraValidator!]! @derivedFrom(field: "staker")
  eraNominators: [StakingEraNominator!]! @derivedFrom(field: "staker")
  payeeType: PayeeType!
  payee: String
  controller: String
}

type StakingValidator @entity {
  id: ID!
  bond: BigInt!
}

type StakingEraNominator @entity {
  id: ID!
  era: StakingEra!
  bond: BigInt!
  staker: StakingStaker!
  nominations: [StakingEraNomination!]! @derivedFrom(field: "nominator")
}

type StakingEraNomination @entity {
  id: ID!
  era: StakingEra!
  amount: BigInt!
  validator: StakingEraValidator!
  nominator: StakingEraNominator!
}

type StakingEraValidator @entity {
  id: ID!
  era: StakingEra!
  validator: StakingValidator!
  nominations: [StakingEraNomination!]! @derivedFrom(field: "validator")
  ownBond: BigInt!
  totalBond: BigInt!
  rewardAmount: BigInt!
  staker: StakingStaker!
}

type StakingEra @entity {
  id: ID!
  index: Int! @index
  start: BigInt! @index
  validators: [StakingEraValidator!]! @derivedFrom(field: "era")
  nominators: [StakingEraNominator!]! @derivedFrom(field: "era")
  nominations: [StakingEraNomination!]! @derivedFrom(field: "era")
}
