import * as productionCalls from '../../production/technical-committee/calls'
import * as stageCalls from '../../stage/technical-committee/calls'
import * as testCalls from '../../test/technical-committee/calls'
import * as devCalls from '../../dev/technical-committee/calls'


export const setMembers = {
	name: 'TechnicalCommittee.set_members',
	v1: productionCalls.setMembers['v1'],
	v33Stage: stageCalls.setMembers['v33'],
	v33Test: testCalls.setMembers['v33'],
	v70Dev: devCalls.setMembers['v70'],
}

export const execute = {
	name: 'TechnicalCommittee.execute',
	v1: productionCalls.execute['v1'],
	v3: productionCalls.execute['v3'],
	v7: productionCalls.execute['v7'],
	v19: productionCalls.execute['v19'],
	v22: productionCalls.execute['v22'],
	v23: productionCalls.execute['v23'],
	v26: productionCalls.execute['v26'],
	v32: productionCalls.execute['v32'],
	v33: productionCalls.execute['v33'],
	v35: productionCalls.execute['v35'],
	v37: productionCalls.execute['v37'],
	v38: productionCalls.execute['v38'],
	v42: productionCalls.execute['v42'],
	v43: productionCalls.execute['v43'],
	v45: productionCalls.execute['v45'],
	v46: productionCalls.execute['v46'],
	v47: productionCalls.execute['v47'],
	v50: productionCalls.execute['v50'],
	v53: productionCalls.execute['v53'],
	v57: productionCalls.execute['v57'],
	v59: productionCalls.execute['v59'],
	v60: productionCalls.execute['v60'],
	v63: productionCalls.execute['v63'],
	v64: productionCalls.execute['v64'],
	v66: productionCalls.execute['v66'],
	v70: productionCalls.execute['v70'],
	v33Stage: stageCalls.execute['v33'],
	v35Stage: stageCalls.execute['v35'],
	v37Stage: stageCalls.execute['v37'],
	v38Stage: stageCalls.execute['v38'],
	v42Stage: stageCalls.execute['v42'],
	v43Stage: stageCalls.execute['v43'],
	v44Stage: stageCalls.execute['v44'],
	v45Stage: stageCalls.execute['v45'],
	v46Stage: stageCalls.execute['v46'],
	v47Stage: stageCalls.execute['v47'],
	v48Stage: stageCalls.execute['v48'],
	v52Stage: stageCalls.execute['v52'],
	v54Stage: stageCalls.execute['v54'],
	v55Stage: stageCalls.execute['v55'],
	v57Stage: stageCalls.execute['v57'],
	v59Stage: stageCalls.execute['v59'],
	v60Stage: stageCalls.execute['v60'],
	v62Stage: stageCalls.execute['v62'],
	v64Stage: stageCalls.execute['v64'],
	v66Stage: stageCalls.execute['v66'],
	v69Stage: stageCalls.execute['v69'],
	v70Stage: stageCalls.execute['v70'],
	v71Stage: stageCalls.execute['v71'],
	v33Test: testCalls.execute['v33'],
	v35Test: testCalls.execute['v35'],
	v37Test: testCalls.execute['v37'],
	v38Test: testCalls.execute['v38'],
	v42Test: testCalls.execute['v42'],
	v43Test: testCalls.execute['v43'],
	v44Test: testCalls.execute['v44'],
	v45Test: testCalls.execute['v45'],
	v46Test: testCalls.execute['v46'],
	v47Test: testCalls.execute['v47'],
	v48Test: testCalls.execute['v48'],
	v52Test: testCalls.execute['v52'],
	v54Test: testCalls.execute['v54'],
	v55Test: testCalls.execute['v55'],
	v57Test: testCalls.execute['v57'],
	v59Test: testCalls.execute['v59'],
	v60Test: testCalls.execute['v60'],
	v62Test: testCalls.execute['v62'],
	v64Test: testCalls.execute['v64'],
	v66Test: testCalls.execute['v66'],
	v69Test: testCalls.execute['v69'],
	v70Test: testCalls.execute['v70'],
	v71Test: testCalls.execute['v71'],
	v70Dev: devCalls.execute['v70'],
}

export const propose = {
	name: 'TechnicalCommittee.propose',
	v1: productionCalls.propose['v1'],
	v3: productionCalls.propose['v3'],
	v7: productionCalls.propose['v7'],
	v19: productionCalls.propose['v19'],
	v22: productionCalls.propose['v22'],
	v23: productionCalls.propose['v23'],
	v26: productionCalls.propose['v26'],
	v32: productionCalls.propose['v32'],
	v33: productionCalls.propose['v33'],
	v35: productionCalls.propose['v35'],
	v37: productionCalls.propose['v37'],
	v38: productionCalls.propose['v38'],
	v42: productionCalls.propose['v42'],
	v43: productionCalls.propose['v43'],
	v45: productionCalls.propose['v45'],
	v46: productionCalls.propose['v46'],
	v47: productionCalls.propose['v47'],
	v50: productionCalls.propose['v50'],
	v53: productionCalls.propose['v53'],
	v57: productionCalls.propose['v57'],
	v59: productionCalls.propose['v59'],
	v60: productionCalls.propose['v60'],
	v63: productionCalls.propose['v63'],
	v64: productionCalls.propose['v64'],
	v66: productionCalls.propose['v66'],
	v70: productionCalls.propose['v70'],
	v33Stage: stageCalls.propose['v33'],
	v35Stage: stageCalls.propose['v35'],
	v37Stage: stageCalls.propose['v37'],
	v38Stage: stageCalls.propose['v38'],
	v42Stage: stageCalls.propose['v42'],
	v43Stage: stageCalls.propose['v43'],
	v44Stage: stageCalls.propose['v44'],
	v45Stage: stageCalls.propose['v45'],
	v46Stage: stageCalls.propose['v46'],
	v47Stage: stageCalls.propose['v47'],
	v48Stage: stageCalls.propose['v48'],
	v52Stage: stageCalls.propose['v52'],
	v54Stage: stageCalls.propose['v54'],
	v55Stage: stageCalls.propose['v55'],
	v57Stage: stageCalls.propose['v57'],
	v59Stage: stageCalls.propose['v59'],
	v60Stage: stageCalls.propose['v60'],
	v62Stage: stageCalls.propose['v62'],
	v64Stage: stageCalls.propose['v64'],
	v66Stage: stageCalls.propose['v66'],
	v69Stage: stageCalls.propose['v69'],
	v70Stage: stageCalls.propose['v70'],
	v71Stage: stageCalls.propose['v71'],
	v33Test: testCalls.propose['v33'],
	v35Test: testCalls.propose['v35'],
	v37Test: testCalls.propose['v37'],
	v38Test: testCalls.propose['v38'],
	v42Test: testCalls.propose['v42'],
	v43Test: testCalls.propose['v43'],
	v44Test: testCalls.propose['v44'],
	v45Test: testCalls.propose['v45'],
	v46Test: testCalls.propose['v46'],
	v47Test: testCalls.propose['v47'],
	v48Test: testCalls.propose['v48'],
	v52Test: testCalls.propose['v52'],
	v54Test: testCalls.propose['v54'],
	v55Test: testCalls.propose['v55'],
	v57Test: testCalls.propose['v57'],
	v59Test: testCalls.propose['v59'],
	v60Test: testCalls.propose['v60'],
	v62Test: testCalls.propose['v62'],
	v64Test: testCalls.propose['v64'],
	v66Test: testCalls.propose['v66'],
	v69Test: testCalls.propose['v69'],
	v70Test: testCalls.propose['v70'],
	v71Test: testCalls.propose['v71'],
	v70Dev: devCalls.propose['v70'],
}

export const vote = {
	name: 'TechnicalCommittee.vote',
	v1: productionCalls.vote['v1'],
	v33Stage: stageCalls.vote['v33'],
	v33Test: testCalls.vote['v33'],
	v70Dev: devCalls.vote['v70'],
}

export const close = {
	name: 'TechnicalCommittee.close',
	v1: productionCalls.close['v1'],
	v53: productionCalls.close['v53'],
	v33Stage: stageCalls.close['v33'],
	v52Stage: stageCalls.close['v52'],
	v33Test: testCalls.close['v33'],
	v52Test: testCalls.close['v52'],
	v70Dev: devCalls.close['v70'],
}

export const disapproveProposal = {
	name: 'TechnicalCommittee.disapprove_proposal',
	v1: productionCalls.disapproveProposal['v1'],
	v33Stage: stageCalls.disapproveProposal['v33'],
	v33Test: testCalls.disapproveProposal['v33'],
	v70Dev: devCalls.disapproveProposal['v70'],
}

export const closeOldWeight = {
	name: 'TechnicalCommittee.close_old_weight',
	v53: productionCalls.closeOldWeight['v53'],
	v52Stage: stageCalls.closeOldWeight['v52'],
	v52Test: testCalls.closeOldWeight['v52'],
	v70Dev: devCalls.closeOldWeight['v70'],
}
